# Generated by Django 3.1.7 on 2021-04-03 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('valentineApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryGift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('order_num', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Wish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order_num', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='msisdn',
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='subs_id',
        ),
        migrations.AddField(
            model_name='subscriber',
            name='phone_number',
            field=models.CharField(default=True, max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='gift',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='gift',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='request',
            name='add_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='recipient',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='recipients', to='valentineApp.subscriber'),
        ),
        migrations.AddField(
            model_name='gift',
            name='category_id',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.DO_NOTHING, to='valentineApp.categorygift'),
        ),
        migrations.AddField(
            model_name='request',
            name='wish',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.DO_NOTHING, to='valentineApp.wish'),
        ),
    ]
