# Generated by Django 3.2 on 2021-04-14 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(verbose_name='Code')),
                ('model', models.CharField(max_length=255, verbose_name='Model')),
                ('speed', models.IntegerField(verbose_name='Speed')),
                ('ram', models.IntegerField(verbose_name='Ram')),
                ('hd', models.IntegerField(verbose_name='HD')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='Price')),
                ('screen', models.IntegerField(verbose_name='Screen')),
            ],
        ),
        migrations.CreateModel(
            name='PC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(verbose_name='Code')),
                ('model', models.CharField(max_length=255, verbose_name='Model')),
                ('speed', models.IntegerField(verbose_name='Speed')),
                ('ram', models.IntegerField(verbose_name='Ram')),
                ('hd', models.IntegerField(verbose_name='HD')),
                ('cd', models.CharField(max_length=255, verbose_name='CD')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='Price')),
            ],
        ),
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(verbose_name='Code')),
                ('model', models.CharField(max_length=255, verbose_name='Model')),
                ('color', models.CharField(max_length=255, null=True, verbose_name='Color')),
                ('type', models.CharField(max_length=255, verbose_name='Type')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='Price')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maker', models.CharField(max_length=255, verbose_name='Maker')),
                ('model', models.CharField(max_length=255, verbose_name='Model')),
                ('type', models.CharField(max_length=255, verbose_name='Type')),
            ],
        ),
    ]
